<template>
  <v-bottom-navigation
    color="primary"
    grow
    app
    :mandatory="true"
    elevation="1"
  >
    <v-btn
      to="/"
      exact
      value="Home"
      class="text-none"
    >
      <v-icon>mdi-home</v-icon>
      Home
    </v-btn>

    <v-btn
      to="/networks"
      value="Networks"
      class="text-none"
    >
      <v-icon>mdi-account-group</v-icon>
      Networks
    </v-btn>

    <v-btn
      to="/pins"
      value="Pins"
      class="text-none"
    >
      <v-icon>mdi-pin</v-icon>
      Pins
    </v-btn>

    <v-btn
      to="/menu"
      value="Menu"
      class="text-none"
    >
      <v-icon>mdi-menu</v-icon>
      Menu
    </v-btn>
  </v-bottom-navigation>
</template>
